db = "freedit.db"
addr = "127.0.0.1:3001"
avatars_path = "./static/avatars"
inn_icons_path = "./static/inn_icons"
cert = "certs/cert.pem"
key = "certs/key.pem"
serve_dir = [
    ["doc", "../doc", "/doc/doc/freedit/index.html"],
    ["rustdoc", "/home/cc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html/", "/rustdoc"]
]