name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
      
jobs:
  cargo:
    name: cargo test, clippy and doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: beta
          components: clippy, rustfmt
      
      - name: Setup cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo test
        run: cargo test
      
      - name: rustfmt
        run: cargo fmt -- --check

      - name: Run rust-clippy
        run: echo "::set-output name=clippy_result::$(cargo clippy --all-features --message-format=json -- -D warnings)"
        id: clippy_run
        continue-on-error: true
      
      - name: Install clippy-sarif sarif-fmt (require cargo)
        if: ${{ contains(steps.clippy_run.outputs.clippy_result, '\"success\":false'}}
        run: |
          cargo install clippy-sarif sarif-fmt
          echo ${{ steps.clippy_run.outputs.clippy_result }} | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt

      - name: Upload analysis results to GitHub
        if: ${{ contains(steps.clippy_run.outputs.clippy_result, '\"success\":false'}}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

      - name: doc build
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cargo doc --no-deps
          echo "<meta http-equiv='refresh' content='0; url=freedit'>" > target/doc/index.html

      - name: Upload artifact
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/doc'

  Deploy:
    needs: cargo
    name: Deploy to GitHub Pages
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: 'github-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main